server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: supergestor
  datasource:
    url: jdbc:h2:mem:supergestor
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    jwt:
      secret: "supergestor-dev-secret-key-change-me-please-123456789"
      expiration-minutes: 480
